version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: odoodb
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postpassword
      POSTGRES_DB: odoodb
    volumes:
      - odoodb-data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: travelagency-backend
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      - .env

volumes:
  odoodb-data:
